[package]
name = "nd-sse-parser"
version = "0.0.0"
edition = "2021"

[dependencies]
tokio-util = { version = "0.7.11", features = [ "codec" ] }

[dev-dependencies]
tokio = { version = "1.38.0", features = [ "macros", "fs", "rt" ] }
tokio-stream = "0.1.15"

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
lto = "fat"
strip = "symbols"
